Fix several bugs
New implementation had been tested with all fuzz scripts in *./examples* since the last commit.

Bugs found and fixed in the new implementation:

build.sh
 - `info` method has been [removed from networkx 3](https://networkx.org/documentation/stable/release/release_3.0.html). *add_edges.py* and *distance.py* give `AttributeError: module 'networkx' has no attribute 'info'`.
 - Incorrect work directory when compling aflgo.

Readme.md
 - Should also install older versions of networkx.
 - Should remind users for libxml2 in another level-1 title.
 - Should info users that the dependencies aren't installed by fuzzing scripts.

afl-2.57b/Makefile
 - Missing link of libm (for math.h)

instrument/aflgo-clang.c
 - Incorrect construction of obj_path

instrument/aflgo-runtime.c
 - Incorrect relative include path

instrument/Makefile
 - Missing "./"

distance/distance_calculator/CMakeLists.txt
 - Incorrect file extension

distance/gen_distance_orig.sh
 - Redundant `set -euo pipefail`. The script has its own error handling processes such as `|| FAIL=1`.
 - Inconsistent behavior with *gen_distance_fast.py* because of `find`. The python script uses `Path.glob`, which won't search recursively without "**/". However GNU find searches the whole directory tree. So use `-maxdepth` to constrain it.

examples
 - All scripts should fit new *gen_distance_orig.sh* (consistent with *gen_distance_fast.py*) and stop abusing $SUBJECT everywhere :(
 - *KTY_Pretty_Printer.sh*, *LMS.sh* and *Palindrome.sh*: https://github.com/trailofbits/cb-multios/pull/86 force it to use clang in cmake/32.cmake and cmake/64.cmake, making $CC and $CXX useless.
 - *libming-CVE-2018-8962.sh* and *libming-CVE-2018-8962.sh*: Without "-fcommon" the linker called by clang will fail. See https://github.com/squaresLab/security-repair-benchmarks/issues/19
 - *libxml2-ef709ce2.sh*: Should undo `set -e` because `cp $SUBJECT/test/dtd* in` needs to ignore directory *$SUBJECT/test/dtds* as normal.